# Generated by Django 4.2.5 on 2023-10-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0002_alter_jop_salay'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='jops',
            field=models.ManyToManyField(to='RMS.jop'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='CS',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jop',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
