# Generated by Django 4.2.5 on 2023-10-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0003_company_jops_alter_cv_title_alter_department_cs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='jops',
            field=models.ManyToManyField(to='RMS.jop'),
        ),
    ]
