# Generated by Django 4.2.5 on 2023-10-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0004_applicant_jops'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cvs',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='RMS.cv'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='depart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='RMS.department'),
        ),
        migrations.AddField(
            model_name='company',
            name='depart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='RMS.department'),
        ),
    ]
