# Generated by Django 4.2.5 on 2023-10-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0005_applicant_cvs_applicant_depart_company_depart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='CS',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='accounting',
        ),
        migrations.RemoveField(
            model_name='department',
            name='engineering',
        ),
        migrations.RemoveField(
            model_name='department',
            name='judiciary',
        ),
        migrations.RemoveField(
            model_name='department',
            name='marketing',
        ),
    ]
