# Generated by Django 4.2.5 on 2023-11-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0007_remove_applicant_cvs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='describtion',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skils',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='title',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='work_experience',
        ),
    ]
