# Generated by Django 4.2.5 on 2023-11-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0009_skils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
