# Generated by Django 4.2.5 on 2023-11-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0010_alter_jop_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='age',
            new_name='birthdate',
        ),
        migrations.AddField(
            model_name='applicant',
            name='cvl',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='skil',
            field=models.ManyToManyField(to='RMS.skils'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('describtion', models.CharField(max_length=20, null=True)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RMS.applicant')),
            ],
        ),
    ]
